### ISSUE TITLE
`./batou secrets edit` broken when creating new environments?

### ISSUE THREAD

**Issue by ctheune** [flyingcircusio/batou#184] opened 2021-06-08 13:07 UTC

**Comment by icemac** [comment] 2021-07-15 12:28
I cannot reproduce this problem, that's what I did:

* copy `examples/tutorial-secrets/environments/gocept.cfg` to `dev.cfg`
* call `env GNUPGHOME=......./src/batou/secrets/tests/fixture/gnupg ./batou secrets edit dev`
  * This allows me to change and save `secrets/dev.cfg`.
  * It also can be edited again.

I found the following problems while poking around:
* When I create a secrets file for a new environment and do not change anything before closing a file in `secrets` is created but it has a length of 0 Bytes. Trying to edit this file fails because it could not be decoded and I get a traceback.
* Creating a secrets file for a new environment and leaving `members` bank prevents `batou` from encrypting the file so it asks me to edit, encrypt or quit. If I choose quit I also end up with a zero bytes long file in `secrets`

Do you mean these kinds of problems?

**Comment by ctheune** [comment] 2021-08-31 09:11
Yeah, sorry, I can't remember in detail and thought it was something like the workflow that you tried and seems to be working.

Would be great if you fixed the smaller issues you noticed.

**Closed** 2021-10-05 11:10 UTC
Labels: gocept
